### ISSUE TITLE
Add isitmaintaned badges

### ISSUE THREAD

**Issue by welpo** [Jieiku/zola-themes-benchmarks#5]
Hi!

Big fan of this repo.

I was going to make a PR, but I don't see how the contents of the README are generated… I guess it's something you do locally.

My suggestion: add a couple of badges to indicate "project health". I recently came across https://isitmaintained.com, which generates pretty cool badges. Using Abridge as an example:

[![Average time to resolve an issue](http://isitmaintained.com/badge/resolution/Jieiku/abridge.svg)](http://isitmaintained.com/project/Jieiku/abridge "Average time to resolve an issue") [![Percentage of issues still open](http://isitmaintained.com/badge/open/Jieiku/abridge.svg)](http://isitmaintained.com/project/Jieiku/abridge "Percentage of issues still open")

What do you think?

Cheers~

**Comment by Jieiku** [comment]
The page is generated using a Linux Bash Script.

I have locally installed containers for google lighthouse, observatory, and yellow lab tools.

The bash script issues commands to these containers via an ssh command and the result is returned.

If you are interested in the Bash scripts I can share it in the repo. There are scripts on one container responsible for creating the page that call scripts on the target container that actually hosts a given tool.

I like the idea of your badges, but one thing I would have to be careful is making the badges column too wide.

You may have noticed that on a desktop each Theme is able to fit on a single line, this was by design and took a little work to accomplish, such as truncating long theme names as well as setting custom labels for the badges, so instead of "open issues" it simply says "open".

I think I could probably replace the existing Open issues and closed issues badges with the percentage based one you show here.

Will give it a try soon, thanks for the ideas.

**Comment by Jieiku** [comment]
I made the changes a moment ago, it will only apply to the github repos, the gitlab or gitea repos will still show just the open and closed totals, because this new isitmaintained badge only apply github repos. The result should post when the script finishes running in 30 minutes or so.

**Comment by Jieiku** [comment]
Well that did not go so good.

**Comment by welpo** [comment]
Thanks for giving it a go.

> the api limit can be circumvented with a github api key, but that means running another tool locally

Huh, I would have expected the images are loaded on the isitmaintained server (with their API), not queried by the end user.

Oh, well!
